#!/bin/sh

export PATH="PREFIX/bin/dwmblocks:$PATH"

dwmblocks_monitor_mpd &

while : ; do
	date '+%F %T dwmblocks started'
	dwmblocks 2>&1
	date '+%F %T dwmblocks died'
done >>~/.cache/logs/dwmblocks.log
