#!/bin/sh

printf "^C3^["

hour=$(date '+%I')
min=$(date '+%M')

if [ "$min" -lt "15" ]; then
    case "$hour" in
        "00") icon="🕛" ;;
        "01") icon="🕐" ;;
        "02") icon="🕑" ;;
        "03") icon="🕒" ;;
        "04") icon="🕓" ;;
        "05") icon="🕔" ;;
        "06") icon="🕕" ;;
        "07") icon="🕖" ;;
        "08") icon="🕗" ;;
        "09") icon="🕘" ;;
        "10") icon="🕙" ;;
        "11") icon="🕚" ;;
        "12") icon="🕛" ;;
        *) icon="Err!";;
    esac
elif [ "$min" -lt "45" ]; then
    case "$hour" in
        "00") icon="🕜" ;;
        "01") icon="🕝" ;;
        "02") icon="🕝" ;;
        "03") icon="🕞" ;;
        "04") icon="🕟" ;;
        "05") icon="🕠" ;;
        "06") icon="🕡" ;;
        "07") icon="🕢" ;;
        "08") icon="🕣" ;;
        "09") icon="🕤" ;;
        "10") icon="🕥" ;;
        "11") icon="🕦" ;;
        "12") icon="🕧" ;;
        *) icon="Err!";;
    esac
else
    case "$hour" in
        "12") icon="🕐" ;;
        "00") icon="🕐" ;;
        "01") icon="🕑" ;;
        "02") icon="🕒" ;;
        "03") icon="🕓" ;;
        "04") icon="🕔" ;;
        "05") icon="🕕" ;;
        "06") icon="🕖" ;;
        "07") icon="🕗" ;;
        "08") icon="🕘" ;;
        "09") icon="🕙" ;;
        "10") icon="🕚" ;;
        "11") icon="🕛" ;;
        *) icon="Err!";;
    esac
fi

date "+%a %d %b clk%R]^d^" | sed "s/clk/$icon/"
