#!/bin/sh

printf "^C4^["

# TODO: clean up code, remove awk
# TODO: add fancy percent bars like in the disk script
printf "%s%s" "" "$(free -h|awk '/^Mem/ { print $3"/"$2 }'|sed s/i//g)"

printf "]^d^\n"
