#!/bin/sh

printf "^C3^["

status="$(mpc status | sed "/^volume/d; /^ERROR/d; s/\[paused\].*/ /; s/\[playing\].*/ /" | tac | tr -d '\n')"

[ -z "$status" ] && printf "" || printf "%s" "$status"

printf "]^d^\n"
