#!/bin/sh

printf "^C0^^B4^" # Set fg/bg color.

# TODO: clean up code, remove awk
# TODO: add fancy percent bars like in the disk script
printf "%s%s\n" "" "$(free -h|awk '/^Mem/ { print $3"/"$2 }'|sed s/i//g)"
