#!/bin/sh

cap=$(cat /sys/class/power_supply/BAT0/capacity)

# TODO: This is slow -v
fg=$(xrdb -query | grep "*color0" | cut -d'#' -f2)
bg=$(xrdb -query | grep "*color2" | cut -d'#' -f2)
# TODO: This is slow -^

fullpx=$((cap/6))
emptpx=$((20-fullpx))

bat="^c#${bg}^^r0,0,28,19^^f4^^c#${fg}^^r0,7,2,4^^r2,4,20,10^^c#${bg}^^r3,5,18,8^^c#${fg}^^r${emptpx},6,${fullpx},6^^b#${bg}^^c#${fg}^^f24^"

status=$(sed "s/Not charging/❌/; s/Charging//; s/[A-Za-z]*//" /sys/class/power_supply/BAT0/status)

printf "%s%s%s%%\n" "$bat" "$status""$cap"
