#!/bin/sh

############################################
# TODO:                                    #
# This should be rewritten to use the xrdb #
# so it also works with non-pywal colors.  #
############################################

# Import the colors
 . "${HOME}/.cache/wal/colors.sh"

for arg in "$@"
do
    case $arg in
	"bg0") printf "^b%s^" "$color0" ;;
	"bg1") printf "^b%s^" "$color1" ;;
	"bg2") printf "^b%s^" "$color2" ;;
	"bg3") printf "^b%s^" "$color3" ;;
	"bg4") printf "^b%s^" "$color4" ;;
	"bg5") printf "^b%s^" "$color5" ;;
	"bg6") printf "^b%s^" "$color6" ;;
	"bg7") printf "^b%s^" "$color7" ;;
	"bg8") printf "^b%s^" "$color8" ;;

	"fg0") printf "^c%s^" "$color0" ;;
	"fg1") printf "^c%s^" "$color1" ;;
	"fg2") printf "^c%s^" "$color2" ;;
	"fg3") printf "^c%s^" "$color3" ;;
	"fg4") printf "^c%s^" "$color4" ;;
	"fg5") printf "^c%s^" "$color5" ;;
	"fg6") printf "^c%s^" "$color6" ;;
	"fg7") printf "^c%s^" "$color7" ;;
	"fg8") printf "^c%s^" "$color8" ;;

	*) printf "^d^" ;
esac
done && printf "\n"
