#!/bin/sh

printf "^C2^ "

vol=$(pamixer --get-volume-human | tr -d '%')

if [ "$vol" = "muted" ] || [ "$vol" -eq 0 ]; then
    printf "🔇"
elif [ "$vol" -gt 66 ]; then
    printf "🔊%3s%%" "$vol"
elif [ "$vol" -gt 33 ]; then
    printf "🔉%3s%%" "$vol"
else
    printf "🔈%3s%%" "$vol"
fi

printf " ^d^\n"
