#!/bin/sh

status="$(mpc status | sed "/^volume/d; /^ERROR/d; s/\[paused\].*/ /; s/\[playing\].*/ /" | tac | tr -d '\n' | cut -c 1-30)"

[ -z "$status" ] && printf "\n" || printf "%s\n" "$status"

