#!/bin/sh

meminfo=$(head -3 /proc/meminfo | tr -d '[:alpha:][:space:]')

temp="${meminfo#:}"
totl="${temp%%:*}"
temp="${temp#*:}"
free="${temp%%:*}"
avai="${meminfo##*:}"

used=$(((totl-avai)/1024))

avepx=$((2+14*avai/totl))
avfpx=$((17-avepx))

frepx=$((2+14*free/totl))
frfpx=$((17-frepx))

bar="^v^^w^^r0,0,9,19^^C8^^r0,2,9,15^^t^^r0,${frepx},4,${frfpx}^^f4^^w^^r0,2,1,15^^w^^f1^^r0,${avepx},4,${avfpx}^^f4^"

printf "%s %s %sM\n" "" "$bar" "$used"
