#!/bin/sh

printf "^C1^"

[ ! -d /sys/class/power_supply/BAT0 ] && printf "^w^^r0,0,28,19^^f4^^w^^r0,7,2,5^^r2,4,20,11^^w^^r3,5,18,9^^w^^f24^ N/A^d^\n" && exit 0

cap=$(cat /sys/class/power_supply/BAT0/capacity)

fullpx=$((cap/6))
emptpx=$((20-fullpx))

bat="^w^^r0,0,28,19^^f4^^w^^r0,7,2,5^^r2,4,20,11^^w^^r3,5,18,9^^w^^r${emptpx},6,${fullpx},7^^f24^"

status=$(sed "s/Not charging/🚫/; s/Charging//; s/Discharging/⏬/; s/Unknown/⁉/; s/Full/✔/; s/[A-Za-z]*//" /sys/class/power_supply/BAT0/status)

printf "%s%s%3s%%" "$bat" "$status" "$cap"

printf "^d^\n"
