#!/bin/sh

hourmin=$(date -d "+15min" '+%I;%M')

if [ "${hourmin#*;}" -gt 30 ]; then
    hour="${hourmin%;*}30"
else
    hour="${hourmin%;*}00"
fi

case "$hour" in
    "0000") icon="🕛" ;;
    "0100") icon="🕐" ;;
    "0200") icon="🕑" ;;
    "0300") icon="🕒" ;;
    "0400") icon="🕓" ;;
    "0500") icon="🕔" ;;
    "0600") icon="🕕" ;;
    "0700") icon="🕖" ;;
    "0800") icon="🕗" ;;
    "0900") icon="🕘" ;;
    "1000") icon="🕙" ;;
    "1100") icon="🕚" ;;
    "1200") icon="🕛" ;;
    "0030") icon="🕧" ;;
    "0130") icon="🕜" ;;
    "0230") icon="🕝" ;;
    "0330") icon="🕞" ;;
    "0430") icon="🕟" ;;
    "0530") icon="🕠" ;;
    "0630") icon="🕡" ;;
    "0730") icon="🕢" ;;
    "0830") icon="🕣" ;;
    "0930") icon="🕤" ;;
    "1030") icon="🕥" ;;
    "1130") icon="🕦" ;;
    "1230") icon="🕧" ;;
    *) icon="Err!";;
esac

date "+%a %d %b clk%R" | sed "s/clk/$icon/"
