#!/bin/sh

printf "^C3^" # Set fg/bg color.

home=$(df -h --output=pcent,avail ~ | tail -1 | tr -s ' ')
root=$(df -h --output=pcent,avail / | tail -1 | tr -s ' ')

hmpct=$(echo "$home" | cut -d'%' -f1)
rtpct=$(echo "$root" | cut -d'%' -f1)

hmfpx=$((1+hmpct/7))
hmepx=$((17-hmfpx))

rtfpx=$((1+rtpct/7))
rtepx=$((17-rtfpx))

hmbar="^v^^w^^r0,0,4,19^^C8^^r0,2,4,15^^t^^r0,${hmepx},4,${hmfpx}^^f4^"
rtbar="^v^^w^^r0,0,4,19^^C8^^r0,2,4,15^^t^^r0,${rtepx},4,${rtfpx}^^f4^"

# TODO: Add back numbers when there is
# more space to fit them (extra bar).
printf "~ %s | / %s" "$hmbar" "$rtbar"

printf "^d^\n"
