#!/bin/bash

# Based on
# http://colby.id.au/calculating-cpu-usage-from-proc-stat/

prev_file='/tmp/cpumon_prev'

printf "💻 "

while read -r cpu; do
    cpu=($cpu)
    id="${cpu[0]}"
    idle="${cpu[4]}"
    total=0
    for value in "${cpu[@]:1:9}"; do
        total=$((total+value))
    done
    prev_total=0
    prev_idle=0
    if [ -f "${prev_file}_${id}" ]; then
        prev=$(<"${prev_file}_${id}")
        prev_total="${prev##* }"
        prev_idle="${prev%% *}"
    fi
    echo "$idle $total" > "${prev_file}_${id}"

    diff_idle=$((idle-prev_idle))
    diff_total=$((total-prev_total))
    diff_usage=$(((1000*(diff_total-diff_idle)/diff_total+5)/10))

######## bar output
    fpx=$((1+diff_usage/7))
    epx=$((17-fpx))
    printf "^v^^w^^r0,0,8,19^^C8^^r0,2,4,15^^t^^r0,%s,4,%s^^f8^" $epx $fpx
######## text output
#    printf "%2s%% " $diff_usage

done <<EOT
    $(grep '^cpu[0-9]\+\s*' /proc/stat)
EOT
printf "\n"
