#!/bin/bash

prev_file='/tmp/cpumon_prev'

while read -r cpu; do
    cpu=($cpu)
    id="${cpu[0]}"
    idle="${cpu[4]}"
    total=0
    for value in "${cpu[@]:1:9}"; do
        total=$((total+value))
    done
    prev_total=0
    prev_idle=0
    if [ -f "${prev_file}_${id}" ]; then
        prev=$(<"${prev_file}_${id}")
        prev_total="${prev##* }"
        prev_idle="${prev%% *}"
    fi
#    echo "$id $idle / $total ; $prev_idle / $prev_total"
    echo "$idle $total" > "${prev_file}_${id}"

    diff_idle=$((idle-prev_idle))
    diff_total=$((total-prev_total))
    diff_usage=$(((1000*(diff_total-diff_idle)/diff_total+5)/10))

    printf "%s%% " $diff_usage
done <<EOT
    $(grep '^cpu[0-9]\+\s*' /proc/stat)
EOT

printf "\n"
